batch_size: 32
charset: "0123456789abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ!#$%&'\"()*+,-./:;<=>?@[]^_`{|}~\\ "
target_path: 'run/checkpoint_weights_iam.pt'
source: "raw_data/IAM"
train_test_split: [2815, 100]
lr: .001
num_epochs: 200
