batch_size: 32
charset: "0123456789abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ!#$%&'\"()*+,-./:;<=>?@[]^_`{|}~\\ "
target_path: 'run/checkpoint_weights_trdg.pt'
source: "raw_data/trdg"
train_test_split: [9500, 500]
lr: .00001
num_epochs: 500
